# Site Meta Data
title: Project Title
author: Münnecke & Vollmers GbR
description: "A short introduction of your project, this will be displayed in the meta description and the main banner area."
keywords:

# Sharing Options
android_accent: "#00CBC4"
google_analytics:

# Site Config
baseurl: ""
url: "http://sharewilly.github.io/sharewilly"

# Theme Settings
hero_image: "images/default.jpg"
homepage: "http://yoursite.com"
download_link: "#"


# Build settings
markdown: kramdown

permalink: none

sass:
  style: :compressed
  compressed: true

gems:
  - jekyll-sitemap
